import { NextResponse } from "next/server";

const GITHUB_TOKEN = process.env.GITHUB_WEBAIBOT_TOKEN!;
const GITHUB_OWNER = process.env.GITHUB_WEBAIBOT_OWNER || "webaibot";

export const revalidate = 60; // cache for 60 seconds

export async function GET() {
  try {
    const headers: Record<string, string> = {
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    };

    if (GITHUB_TOKEN) {
      headers.Authorization = `Bearer ${GITHUB_TOKEN}`;
    }

    // Fetch all public repos from webaibot, sorted by newest first
    const res = await fetch(
      `https://api.github.com/users/${GITHUB_OWNER}/repos?sort=created&direction=desc&per_page=100&type=public`,
      { headers, next: { revalidate: 60 } }
    );

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      console.error("GitHub repos fetch error:", err);
      return NextResponse.json(
        { error: "Failed to fetch repositories" },
        { status: res.status }
      );
    }

    const repos = await res.json();

    // Filter and map to only include bot repos (exclude "cortex" and other non-bot repos)
    const botRepos = repos
      .filter((repo: any) => repo.name !== ".github" && repo.name !== GITHUB_OWNER)
      .map((repo: any) => ({
        id: repo.id,
        name: repo.name,
        description: repo.description || "AI Bot generated by WebAI",
        url: repo.html_url,
        cloneUrl: repo.clone_url,
        stars: repo.stargazers_count,
        language: repo.language,
        createdAt: repo.created_at,
        updatedAt: repo.updated_at,
        size: repo.size,
      }));

    return NextResponse.json({ repos: botRepos, total: botRepos.length });
  } catch (err) {
    console.error("GitHub repos error:", err);
    return NextResponse.json(
      { error: "Failed to fetch repositories" },
      { status: 500 }
    );
  }
}

